services:
  frontend:
    build: ./frontend
    container_name: push_frontend
    expose:
      - "5173"
  db:
    image: postgres:16
    container_name: push_postgres
    restart: always
    environment:
      POSTGRES_DB: pushdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
    container_name: push_backend
    restart: always
    depends_on:
      - db
      - frontend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pushdb
    ports:
      - "8001:8000"
  
  nginx:
    image: nginx:alpine
    container_name: push_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
